[package]
name = "srs2dge"
version = "0.2.0"
edition = "2021"
description = "Simple Rust 2D Game Engine"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
glsl = ["wgpu/glsl", "naga/glsl-in"]
spirv = ["wgpu/spirv", "naga/spv-in"]
fontloader = ["font-loader"]

[dependencies]
# logging
log = "0.4"
colorful = "0.2"
# graphics
wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "af259aa1", features = [
	"webgl",
] }
naga = { git = "https://github.com/gfx-rs/naga", rev = "1aa91549", features = [
	"wgsl-in",
	"validate",
] }
winit = "0.26"
glam = { version = "0.20", features = ["serde", "bytemuck"] }
main_game_loop = "0.3"
# resources
image = "0.24"
fontsdf = { path = "../fontsdf" }
font-loader = { version = "0.11", optional = true }
# data
serde = { version = "1.0", features = ["derive"] }
rapid-qoi = "0.6"
integer-sqrt = "0.1"
bytemuck = { version = "1.9", features = ["derive"] }


[dev-dependencies]
rand = "0.8"
static_res = "0.1"
anyhow = "1.0"
pollster = "0.2"
instant = "0.1"
# rapier2d = "0.11"


[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"
