[package]
name = "srs2dge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"

parking_lot = "0.11.2"
rand = "0.8.4"

glium = "0.31.0"
winit = "0.26.0"
glam = "0.20.1"

image = "0.23.14"
fontdue = "0.6.2"
static_res = { git = "https://github.com/Overpeek/static_res" }
