[package]
name = "srs2dge"
version = "0.2.0"
edition = "2021"
description = "Simple Rust 2D Game Engine"
license = "MIT"

[features]
default = ["presets", "gizmos", "res"]
dynamic = ["srs2dge-link-dynamic"]
presets = ["srs2dge-link-static/presets"]
gizmos = ["srs2dge-link-static/gizmos"]
res = ["srs2dge-link-static/res"]

[dependencies]
srs2dge-link-static = { path = "crates/srs2dge-link-static", version = "0.2" }
srs2dge-link-dynamic = { path = "crates/srs2dge-link-dynamic", version = "0.2", optional = true }

[dev-dependencies]
instant = "0.1"
# rapier2d = "0.11"

[workspace]
members = ["crates/*"]
