[package]
name = "srs2dge"
version = "0.1.0"
edition = "2021"
description = "Simple Rust 2D Game Engine"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"

parking_lot = "0.12.0"
rand = "0.8.4"

glium = "0.31.0"
winit = "0.26.1"
glam = { version = "0.20.1", features = ["serde"] }
main_game_loop = "0.1.0"

image = "0.24.1"
fontdue = "0.7.2"
font-loader = "0.11.0"
static_res = "0.1.0"

serde = { version = "1.0.136", features = ["derive"] }
rapid-qoi = "0.6.1"
integer-sqrt = "0.1.5"
