[package]
name = "srs2dge-res"
version = "0.2.0"
edition = "2021"
description = "srs2dge static resources"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
